version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  nonebot876210974:
    image: hzgood/docker-nb-cli
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./:/app/"
      - "../cqhttp876210974:/app/cqhttp/"
    env_file:
      - ".env.prod876210974" # fastapi 使用的环境变量文件
    working_dir: "/app"
    # network_mode: bridge
    depends_on:
      - db
    command: ["bash","start.sh"]
    # command: ["sleep","30000"]
  db876210974:
    image: redis
    ports:
      - 6379:6380
    volumes:
      - ./redis/data876210974:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs876210974:/logs
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]